### ISSUE TITLE
Any updates planned?

### ISSUE THREAD

**Issue by 1dot44mb** [takeshinoda/thinreports-rails#3]
Dear @takeshinoda,

Thanks for this great gem.

I would like to know if you plan to update this gem as 'thinreports' and other gems have updated versions (prawl, etc.)?

Thanks.

**Comment by takeshinoda** [comment]
Now, release 0.2.0. 
https://rubygems.org/gems/thinreports-rails/versions/0.2.0

**Comment by 1dot44mb** [comment]
Thank you very much. 
Regards.
